# Generated by Django 3.2.13 on 2022-04-27 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='user_id',
            new_name='user',
        ),
    ]
